# Generated by Django 4.2 on 2023-05-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_padaria_options_alter_padaria_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padaria',
            old_name='endereco',
            new_name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='padaria',
            name='fantasy_name',
        ),
    ]
