# Generated by Django 4.2 on 2023-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_rename_endereco_padaria_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padaria',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
