# Generated by Django 4.2 on 2023-05-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_alter_planoassinatura_servings_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padaria',
            name='plano_assinatura',
        ),
        migrations.AddField(
            model_name='padaria',
            name='plano_assinatura',
            field=models.ManyToManyField(blank=True, related_name='padaria', to='authors.planoassinatura'),
        ),
    ]
