# Generated by Django 4.2 on 2023-05-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_remove_padaria_plano_assinatura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planoassinatura',
            old_name='servings_unit',
            new_name='pessoas_servidas',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nome',
        ),
    ]
