# Generated by Django 4.2 on 2023-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_rename_servings_unit_planoassinatura_pessoas_servidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padaria',
            name='telefone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
