# Generated by Django 4.2 on 2023-05-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_rename_servings_unit_planoassinatura_pessoas_servidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoassinatura',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planoassinatura',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
