# Generated by Django 4.2 on 2023-05-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_alter_padaria_telefone'),
        ('authors', '0012_alter_planoassinatura_descricao_and_more'),
    ]

    operations = [
    ]
