# Generated by Django 4.2 on 2023-06-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0014_diasemana_assinatura_assinado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padaria',
            name='plano_assinatura',
            field=models.ManyToManyField(blank=True, related_name='padaria_planos', to='authors.planoassinatura'),
        ),
    ]
