# Generated by Django 4.2 on 2023-06-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0015_alter_padaria_plano_assinatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='horario_entrega',
        ),
    ]
