# Generated by Django 4.2 on 2023-06-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0016_remove_assinatura_dias_semana_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaSemana',
        ),
    ]
