# Generated by Django 4.2 on 2023-11-29 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0018_alter_endereco_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoassinatura',
            name='pessoas_servidas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='planoassinatura',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
